local menu = require("game.screens.menu")

return function(test)
    test("menu supports mouse and keyboard choices and resets to Play on entry", function()
        menu.enter()
        assert(menu.keypressed("return") == "play")
        menu.keypressed("down")
        assert(menu.keypressed("return") == "quit")
        menu.keypressed("down")
        assert(menu.keypressed("space") == "play")
        menu.keypressed("up")
        assert(menu.keypressed("kpenter") == "quit")
        menu.keypressed("tab")
        assert(menu.keypressed("return") == "play")
        menu.mousemoved(640, 477)
        assert(menu.keypressed("return") == "quit")
        assert(menu.mousepressed(640, 409, 1) == "play")
        assert(menu.mousepressed(640, 477, 1) == "quit")
        assert(not menu.mousepressed(640, 477, 2))
        assert(not menu.mousepressed(0, 0, 1))
        assert(not menu.keypressed("a"))
        menu.enter()
        assert(menu.keypressed("return") == "play")
    end)
end
